name: Deploy to heroku.

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: flows-server
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Release docker container to Heroku.
        run: |
          echo $HEROKU_API_KEY | docker login --username=$HEROKU_EMAIL registry.heroku.com --password-stdin
          docker tag flows-server registry.heroku.com/${HEROKU_APP_NAME}/web
          docker push registry.heroku.com/${HEROKU_APP_NAME}/web
          heroku container:release web --app $HEROKU_APP_NAME
        env:
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
