name: Build and deploy
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ocaml/setup-ocaml@v2
      with:
        dune-cache: true
    - name: Install dependencies
      run: opam list --short --color=never --required-by=liquidsoap-flows-server | xargs opam install -y
    - name: Install
      run: opam install liquidsoap-flows-server
