name: Build
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        ocaml-version: ['4.14.0']
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - uses: ocaml/setup-ocaml@v2
      with:
        ocaml-version: ${{ matrix.ocaml-version }}
    - run: opam pin add -n .
    - name: Install dependencies
      run: opam depext -yt liquidsoap-flows-server
    - name: Build and install
      run: opam install -t .
      env:
        PGUSER: postgres
        PGPASSWORD: postgres
        PGHOST: localhost
        PGDATABASE: postgres
